--- #YAML:1.0
name:               CGI-OptimalQuery
version:            0.03
abstract:           rich HTML viewer for your SQL select queries
author:
    - Philip Collins (Philip.Collins@unh.edu)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DBD::SQLite:        0
    DBI:                0
    JSON::XS:           0
    Parse::RecDescent:  0
    Test::Simple:       0.44
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
